### PR TITLE
update support typescript

### PR DESCRIPTION
**Pull request by RibikiH**
Adding types in package.json and declare file for typescript

### CODE REVIEW

**Comment by gignupg** [comment]
@RibikiH Thanks for adding types to this package and sorry for my late response!

I'll take a look at it tonight and release a new version to npm if everything works xD

**Comment by gignupg** [comment]
@RibikiH It's merged! Before releasing a new version to npm however, I'll do some restructuring of the readme and add more precise types for the encoding and language. I'll post an update here once I published the new changes to npm!

**Comment by RibikiH** [comment]
@gignupg Thanks for merging.

**Comment by gignupg** [comment]
@RibikiH I finally released the new version to NPM xD

**Comment by RibikiH** [comment]
@gignupg thank you so much 👍

**Pull request merged**
